name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master

        - name: Package
          run: |
              zip -r package.zip icons icon.png preview.png README_en_US.md README.md theme.css theme.js theme.json
    
        - name: Create Release
          uses: ncipollo/release-action@v1.13.0
          with:
            allowUpdates: true
            artifactErrorsFailBuild: true
            artifacts: "package.zip"
            token: ${{ secrets.GITHUB_TOKEN }}